INSERT OR IGNORE INTO departments (id, name, description, active) VALUES
(1, 'Infraestrutura', 'Rede, conectividade, VPN e equipamentos físicos.', 1),
(2, 'Sistemas', 'Aplicações, autenticação, software e bancos de dados.', 1),
(3, 'Segurança da Informação', 'Incidentes e suspeitas de segurança.', 1);

INSERT OR IGNORE INTO employees (id, department_id, name, active) VALUES
(1, 1, 'Rafael', 1),
(2, 1, 'Marina', 1),
(3, 2, 'Lucas', 1),
(4, 2, 'Camila', 1),
(5, 3, 'Bruno', 1),
(6, 3, 'Isabela', 1);

INSERT OR IGNORE INTO categories (id, department_id, name, description, active) VALUES
(1, 1, 'Rede e Internet', 'Problemas de internet, Wi-Fi, DNS e rede local.', 1),
(2, 1, 'VPN', 'Falhas de conexão e estabilidade da VPN.', 1),
(3, 1, 'Hardware', 'Problemas físicos com computadores e periféricos.', 1),
(4, 2, 'Acesso e Autenticação', 'Login, senha, credenciais e bloqueios de conta.', 1),
(5, 2, 'Software e Aplicações', 'Falhas em programas, sistemas operacionais e aplicações.', 1),
(6, 2, 'Banco de Dados', 'Conexões, consultas e indisponibilidade de bancos.', 1),
(7, 3, 'Segurança', 'Phishing, malware, acessos suspeitos e incidentes.', 1);

INSERT OR IGNORE INTO classification_examples (category_id, text, source, active) VALUES
(1, 'A internet do laboratório caiu.', 'seed', 1),
(1, 'Estou conectado no Wi-Fi, mas nenhum site abre.', 'seed', 1),
(1, 'Meu notebook não consegue conectar na rede sem fio.', 'seed', 1),
(1, 'A rede está conectada, porém estou sem acesso à internet.', 'seed', 1),
(2, 'A VPN desconecta depois de alguns minutos.', 'seed', 1),
(2, 'Não consigo conectar na VPN corporativa.', 'seed', 1),
(2, 'O acesso remoto pela VPN apresenta erro.', 'seed', 1),
(3, 'O teclado do computador não está funcionando.', 'seed', 1),
(3, 'O monitor não liga.', 'seed', 1),
(3, 'Meu notebook não reconhece o mouse.', 'seed', 1),
(3, 'O computador não está ligando.', 'seed', 1),
(4, 'Não consigo autenticar no GitHub com minha conta.', 'seed', 1),
(4, 'Minha senha não funciona no login.', 'seed', 1),
(4, 'Minha conta está bloqueada.', 'seed', 1),
(4, 'Não consigo fazer login no sistema.', 'seed', 1),
(5, 'O Docker Desktop fecha ao iniciar no Windows.', 'seed', 1),
(5, 'O VS Code não reconhece o Python.', 'seed', 1),
(5, 'O aplicativo fecha sozinho quando abre.', 'seed', 1),
(5, 'O programa apresenta erro durante a inicialização.', 'seed', 1),
(6, 'Não consigo conectar no banco de dados.', 'seed', 1),
(6, 'A consulta SQL está retornando erro.', 'seed', 1),
(6, 'O Oracle não aceita a conexão.', 'seed', 1),
(6, 'O PostgreSQL está indisponível.', 'seed', 1),
(7, 'Recebi um e-mail de phishing.', 'seed', 1),
(7, 'Minha conta apresentou um login que não reconheço.', 'seed', 1),
(7, 'O antivírus detectou um arquivo suspeito.', 'seed', 1),
(7, 'Acredito que minha conta foi comprometida.', 'seed', 1);

INSERT OR IGNORE INTO category_keywords (category_id, keyword, weight, active) VALUES
(1, 'wi-fi', 1.5, 1),
(1, 'wifi', 1.5, 1),
(1, 'internet', 1.5, 1),
(1, 'rede', 1.2, 1),
(1, 'dns', 1.5, 1),
(1, 'roteador', 1.4, 1),
(1, 'site', 0.6, 1),
(2, 'vpn', 2.0, 1),
(2, 'túnel', 1.5, 1),
(2, 'acesso remoto', 1.3, 1),
(3, 'teclado', 1.4, 1),
(3, 'mouse', 1.3, 1),
(3, 'monitor', 1.4, 1),
(3, 'impressora', 1.4, 1),
(3, 'hardware', 1.5, 1),
(3, 'computador', 0.6, 1),
(3, 'notebook', 0.6, 1),
(4, 'senha', 1.5, 1),
(4, 'login', 1.5, 1),
(4, 'autenticar', 1.5, 1),
(4, 'autenticação', 1.5, 1),
(4, 'credencial', 1.4, 1),
(4, 'conta', 0.8, 1),
(4, 'bloqueada', 1.0, 1),
(5, 'docker', 1.6, 1),
(5, 'vs code', 1.6, 1),
(5, 'vscode', 1.6, 1),
(5, 'python', 1.0, 1),
(5, 'windows', 0.8, 1),
(5, 'aplicativo', 1.1, 1),
(5, 'programa', 1.0, 1),
(5, 'software', 1.3, 1),
(6, 'sql', 1.5, 1),
(6, 'oracle', 1.6, 1),
(6, 'postgresql', 1.6, 1),
(6, 'postgres', 1.6, 1),
(6, 'mysql', 1.6, 1),
(6, 'banco de dados', 1.5, 1),
(6, 'database', 1.4, 1),
(7, 'phishing', 1.8, 1),
(7, 'malware', 1.8, 1),
(7, 'vírus', 1.6, 1),
(7, 'invasão', 1.6, 1),
(7, 'suspeito', 1.1, 1),
(7, 'comprometida', 1.5, 1),
(7, 'segurança', 1.2, 1);
